// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OData_webapi_netcore6.Services;

#nullable disable

namespace OData_webapi_netcore6.Migrations
{
    [DbContext(typeof(OdataNet6TutorialContext))]
    [Migration("20220205103344_initiL")]
    partial class initiL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("OData_webapi_netcore6.Models.Authors", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("AuthorGuid");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("OData_webapi_netcore6.Models.Books", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("BookGuid");

                    b.Property<Guid?>("AuthorGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesSold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorGuid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("OData_webapi_netcore6.Models.Books", b =>
                {
                    b.HasOne("OData_webapi_netcore6.Models.Authors", "Authors")
                        .WithMany("Books")
                        .HasForeignKey("AuthorGuid");

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("OData_webapi_netcore6.Models.Authors", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
